#!/usr/bin/env python
import socket

#My own machine's IP
s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
s.connect(("8.8.8.8",80))
src_ip = s.getsockname()[0] #own machine IP
s.close()


client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
dest_ip = socket.gethostbyname("elsrv2.cs.umass.edu")   #host name
port = 80  #port
address = (dest_ip,port)
client.connect(address) #establish connection

#Get the website and store the session and token
client.sendall("GET /accounts/login/?next=/fakebook/ HTTP/1.0\r\n"
"Host: elsrv2.cs.umass.edu\r\n\r\n")
info=""
data = client.recv(4096)
while data:
    info = info+data
    data = client.recv(4096)
client.close()
print info

